package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const commandDocsGenerator = "go run ./cmd/polygolem_docs"

type commandDocFlag struct {
	name        string
	shorthand   string
	valueType   string
	defaultText string
	usage       string
}

// GenerateCommandsMarkdown renders the checked-in CLI command reference from
// Cobra metadata. Keep this deterministic: generated docs are a build artifact.
func GenerateCommandsMarkdown(root *cobra.Command) string {
	prepareCommandDocs(root)

	var b strings.Builder
	b.WriteString("# Commands\n\n")
	b.WriteString("Generated command reference for `polygolem`.\n\n")
	b.WriteString("> Generated by `" + commandDocsGenerator + "`. Do not edit by hand.\n\n")
	b.WriteString("## Conventions\n\n")
	b.WriteString("- All commands accept `--json` to emit structured JSON.\n")
	b.WriteString("- Flag semantics come from the Cobra command tree in `internal/cli`.\n")
	b.WriteString("- Authenticated commands consume the environment variables listed below.\n")
	b.WriteString("- Trading commands use deposit-wallet signing only (type 3 / POLY_1271).\n\n")
	writeEnvironmentVariablesSection(&b)
	writeAutomationSmokeCheckSection(&b)
	b.WriteString("## Command Tree\n\n")
	b.WriteString("```text\n")
	writeCommandTree(&b, root, 0)
	b.WriteString("```\n\n")
	b.WriteString("## Command Reference\n\n")
	for _, cmd := range commandList(root) {
		writeCommandSection(&b, cmd)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeEnvironmentVariablesSection(b *strings.Builder) {
	b.WriteString("## Environment Variables\n\n")
	b.WriteString("| Variable | Required for |\n")
	b.WriteString("|---|---|\n")
	b.WriteString("| `POLYMARKET_PRIVATE_KEY` | All authenticated CLOB and deposit-wallet commands. |\n")
	b.WriteString("| `RELAYER_API_KEY` | Optional pre-provisioned V2 relayer auth. Live deposit-wallet commands auto-mint and persist this key when it is missing. |\n")
	b.WriteString("| `RELAYER_API_KEY_ADDRESS` | Owner address for `RELAYER_API_KEY`. |\n")
	b.WriteString("| `POLYGOLEM_RELAYER_ENV_FILE` | Optional target/source env file for auto-minted V2 relayer credentials. |\n")
	b.WriteString("| `POLYMARKET_BUILDER_API_KEY` | Legacy builder-relayer fallback for deposit-wallet relayer commands. |\n")
	b.WriteString("| `POLYMARKET_BUILDER_SECRET` | Legacy builder-relayer fallback for deposit-wallet relayer commands. |\n")
	b.WriteString("| `POLYMARKET_BUILDER_PASSPHRASE` | Legacy builder-relayer fallback for deposit-wallet relayer commands. |\n")
	b.WriteString("| `POLYMARKET_CLOB_API_KEY` | Optional pre-provisioned CLOB L2 key. Polygolem can create or derive the EOA-bound CLOB key on demand. |\n")
	b.WriteString("| `POLYMARKET_CLOB_SECRET` | Secret for `POLYMARKET_CLOB_API_KEY`. |\n")
	b.WriteString("| `POLYMARKET_CLOB_PASSPHRASE` | Passphrase for `POLYMARKET_CLOB_API_KEY`. |\n")
	b.WriteString("| `POLYMARKET_BUILDER_CODE` | Optional CLOB V2 order builder attribution bytes32. |\n")
	b.WriteString("| `POLYMARKET_CLOB_BUILDER_CODE` | Alias for `POLYMARKET_BUILDER_CODE`. |\n")
	b.WriteString("| `POLYMARKET_RELAYER_URL` | Optional relayer URL override. |\n\n")
	b.WriteString("Short-form `CLOB_API_KEY`, `CLOB_SECRET`, `CLOB_PASSPHRASE`, `CLOB_PASS_PHRASE`, `BUILDER_API_KEY`, `BUILDER_SECRET`, and `BUILDER_PASS_PHRASE` are also accepted for local automation.\n\n")
}

func writeAutomationSmokeCheckSection(b *strings.Builder) {
	b.WriteString("## Automation Smoke Check\n\n")
	b.WriteString("Use JSON output in scripts and fail fast when parsing command output:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString("polygolem --json version | jq .\n")
	b.WriteString("```\n\n")
}

// GenerateCLIReferenceMDX renders the Starlight CLI overview from Cobra
// metadata. Detailed flags stay in docs/COMMANDS.md to avoid two manual refs.
func GenerateCLIReferenceMDX(root *cobra.Command) string {
	prepareCommandDocs(root)

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: CLI Commands\n")
	b.WriteString("description: Generated polygolem command tree for Gamma discovery, CLOB trading, Data API analytics, streams, bridge, paper mode, and deposit wallets.\n")
	b.WriteString("---\n\n")
	b.WriteString("{/* Generated by `" + commandDocsGenerator + "`. Do not edit by hand. */}\n\n")
	b.WriteString("## Command Tree\n\n")
	b.WriteString("```text\n")
	writeCommandTree(&b, root, 0)
	b.WriteString("```\n\n")
	b.WriteString("## Top-Level Commands\n\n")
	b.WriteString("| Command | Description |\n")
	b.WriteString("|---|---|\n")
	for _, child := range sortedCommands(root.Commands()) {
		b.WriteString("| `" + child.CommandPath() + "` | " + markdownTableText(commandDescription(child)) + " |\n")
	}
	b.WriteString("\n")
	b.WriteString("## Safety\n\n")
	b.WriteString("Trading commands always use deposit-wallet signing (type 3 / POLY_1271). The old `--signature-type` flow is intentionally absent.\n\n")
	b.WriteString("Every command accepts `--json` and `--help`. The canonical generated flag reference lives in [`docs/COMMANDS.md`](https://github.com/TrebuchetDynamics/polygolem/blob/main/docs/COMMANDS.md).\n")
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func prepareCommandDocs(root *cobra.Command) {
	for _, cmd := range commandList(root) {
		cmd.InitDefaultHelpFlag()
		cmd.DisableAutoGenTag = true
	}
}

func commandList(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(*cobra.Command)
	walk = func(cmd *cobra.Command) {
		if cmd.Hidden {
			return
		}
		out = append(out, cmd)
		for _, child := range sortedCommands(cmd.Commands()) {
			walk(child)
		}
	}
	walk(root)
	return out
}

func sortedCommands(commands []*cobra.Command) []*cobra.Command {
	out := make([]*cobra.Command, 0, len(commands))
	for _, cmd := range commands {
		if !cmd.Hidden {
			out = append(out, cmd)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Name() < out[j].Name()
	})
	return out
}

func writeCommandTree(b *strings.Builder, cmd *cobra.Command, depth int) {
	indent := strings.Repeat("  ", depth)
	if depth == 0 {
		b.WriteString(cmd.Name())
	} else {
		b.WriteString(indent + cmd.Name())
	}
	if desc := commandDescription(cmd); desc != "" {
		b.WriteString(" - " + desc)
	}
	b.WriteByte('\n')
	for _, child := range sortedCommands(cmd.Commands()) {
		writeCommandTree(b, child, depth+1)
	}
}

func writeCommandSection(b *strings.Builder, cmd *cobra.Command) {
	b.WriteString("### " + cmd.CommandPath() + "\n\n")
	if desc := commandDescription(cmd); desc != "" {
		b.WriteString(desc + "\n\n")
	}
	if long := strings.TrimSpace(cmd.Long); long != "" && long != strings.TrimSpace(cmd.Short) {
		b.WriteString(long + "\n\n")
	}
	b.WriteString("**Usage:**\n\n")
	b.WriteString("```bash\n")
	b.WriteString(cmd.UseLine() + "\n")
	b.WriteString("```\n\n")
	if children := sortedCommands(cmd.Commands()); len(children) > 0 {
		b.WriteString("**Subcommands:**\n\n")
		b.WriteString("| Command | Description |\n")
		b.WriteString("|---|---|\n")
		for _, child := range children {
			b.WriteString("| `" + child.CommandPath() + "` | " + markdownTableText(commandDescription(child)) + " |\n")
		}
		b.WriteString("\n")
	}
	flags := commandFlags(cmd)
	if len(flags) > 0 {
		b.WriteString("**Flags:**\n\n")
		b.WriteString("| Flag | Type | Default | Description |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, flag := range flags {
			b.WriteString("| `" + flagDisplay(flag) + "` | `" + flag.valueType + "` | `" + flag.defaultText + "` | " + markdownTableText(flag.usage) + " |\n")
		}
		b.WriteString("\n")
	}
}

func commandDescription(cmd *cobra.Command) string {
	if short := strings.TrimSpace(cmd.Short); short != "" {
		return short
	}
	if long := strings.TrimSpace(cmd.Long); long != "" {
		return firstLine(long)
	}
	return ""
}

func firstLine(value string) string {
	value = strings.TrimSpace(value)
	if idx := strings.IndexByte(value, '\n'); idx >= 0 {
		return strings.TrimSpace(value[:idx])
	}
	return value
}

func commandFlags(cmd *cobra.Command) []commandDocFlag {
	seen := map[string]bool{}
	var flags []commandDocFlag
	addFlags := func(flagSet *pflag.FlagSet) {
		if flagSet == nil {
			return
		}
		flagSet.VisitAll(func(flag *pflag.Flag) {
			if flag.Hidden || seen[flag.Name] {
				return
			}
			seen[flag.Name] = true
			flags = append(flags, commandDocFlag{
				name:        flag.Name,
				shorthand:   flag.Shorthand,
				valueType:   flag.Value.Type(),
				defaultText: flagDefault(flag),
				usage:       flag.Usage,
			})
		})
	}
	addFlags(cmd.LocalFlags())
	addFlags(cmd.InheritedFlags())
	sort.Slice(flags, func(i, j int) bool {
		return flags[i].name < flags[j].name
	})
	return flags
}

func flagDisplay(flag commandDocFlag) string {
	if flag.shorthand != "" {
		return fmt.Sprintf("-%s, --%s", flag.shorthand, flag.name)
	}
	return "--" + flag.name
}

func flagDefault(flag *pflag.Flag) string {
	if flag.DefValue == "" {
		return `""`
	}
	return flag.DefValue
}

func markdownTableText(value string) string {
	value = strings.TrimSpace(value)
	value = strings.ReplaceAll(value, "\n", "<br>")
	value = strings.ReplaceAll(value, "|", "\\|")
	if value == "" {
		return " "
	}
	return value
}
